T = {
"How to read the table":"So liest man die Tabelle","Show hints on column headers":"Hinweise in den Spaltenköpfen anzeigen","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"Jede Wallet wird mit Käufern an derselben Kurvenposition verglichen; das Hauptkriterium ist der Überschuss — pessimistische Trefferquote minus Marktquote. Die Validierung ist ein Zeitraum, der nie für die Auswahl benutzt wurde.",
"Compact columns":"Kompakte Spalten","All columns":"Alle Spalten",
"Sign in":"Anmelden","API keys":"API-Schlüssel","Key name":"Schlüsselname","Create key":"Schlüssel erstellen","name":"Name","prefix":"Präfix","calls":"Aufrufe","last used":"zuletzt genutzt","Revoke":"Widerrufen","No keys yet":"Noch keine Schlüssel","Copy the key now — it is shown once":"Schlüssel jetzt kopieren — er wird nur einmal angezeigt",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"Schlüssel im Header X-API-Key verwenden. Endpunkte: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 Anfragen pro Minute.",
"My lists":"Meine Listen","New list name":"Name der neuen Liste","Create":"Erstellen","Select or create a list":"Liste auswählen oder erstellen","Add selected to my list…":"Auswahl zu meiner Liste hinzufügen…","Add to my list…":"Zu meiner Liste hinzufügen…","Which list?":"Welche Liste?","Remove":"Entfernen","Delete list":"Liste löschen","Delete this list?":"Diese Liste löschen?","Notes":"Notizen","Save":"Speichern","added to":"hinzugefügt zu","wallets":"Wallets","Sign in to keep your own lists":"Anmelden, um eigene Listen zu führen","Rename":"Umbenennen","No lists yet":"Noch keine Listen","Export":"Exportieren","History":"Verlauf",
"Overview":"Übersicht","List":"Liste","Candidates":"Kandidaten","Log":"Protokoll","Rejected":"Abgelehnt","Lists":"Externe Listen","Rules":"Regeln","Fast · ×2 in 1 h":"Fast · ×2 in 1 h","Pickers · pool or ×5 in 24 h":"Picker · Pool oder ×5 in 24 h","Top candidates":"Top-Kandidaten","Open candidates →":"Kandidaten öffnen →","Your list":"Ihre Liste","Apply rules":"Regeln anwenden","Export list":"Liste exportieren","Recompute":"Neu berechnen","Market baselines":"Markt-Basiswerte","Market baselines (last recompute)":"Markt-Basiswerte (letzte Berechnung)","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"Trefferquote des Gesamtmarkts nach Kurvenposition — jede Wallet wird an Käufern derselben Position gemessen.",
"address…":"Adresse…","all":"alle","Add all matching to list":"Alle passenden zur Liste hinzufügen","Add selected":"Auswahl hinzufügen","Reject selected":"Auswahl ablehnen","Save rules":"Regeln speichern",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"Externe Listen aus lists/*.txt nach unserem Scoring. „Treffer“ = ×2 innerhalb 1 h (fast) oder Pool/×5 (picker) über alle Signale der Liste; „erwartet“ = was der Markt an denselben Kurvenpositionen liefern würde.",
"signals":"Signale","candidates":"Kandidaten","in list":"in Liste","rejected":"abgelehnt","data as of":"Daten vom","empty":"leer","sign out":"abmelden","Signals":"Signale","Wallets":"Wallets","In list":"In Liste","Data":"Daten","addresses in profile":"Adressen im Profil","showing first":"angezeigt: erste","Filter: matching":"Filter: passend","of":"von","Preset: fast":"Voreinstellung: fast","Preset: pickers":"Voreinstellung: Picker","Soft preset":"Weiche Voreinstellung","Reset":"Zurücksetzen","from":"von","to":"bis","in list ":"in Liste ","rejected ":"abgelehnt ",
"added":"hinzugefügt","removed":"entfernt","restored":"wiederhergestellt","recompute":"Neuberechnung","rules":"Regeln","when":"Zeit","action":"Aktion","address":"Adresse","profile":"Profil","reason":"Grund","by":"durch","recheck after":"erneut prüfen nach","restore":"wiederherstellen","list":"Liste","size":"Größe","in data":"in Daten","n≥5":"n≥5","hit":"Treffer","expected":"erwartet","×market":"×Markt","median excess":"Überschuss (Median)","share excess>0":"Anteil Überschuss>0","top-100":"Top-100","top-500":"Top-500","ranked":"gerankt","median rank":"Rang (Median)","val signals":"Validierungssignale","val hit":"Validierungstreffer","val expected":"Validierung erwartet","no data — put lists into lists/*.txt and recompute":"keine Daten — Listen in lists/*.txt ablegen und neu berechnen","Profile “fast”":"Profil „fast“","Profile “pickers”":"Profil „Picker“","Signals (":"Signale (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"jeder Punkt ist ein Signal in der Zeit; Höhe = log₂(Hoch innerhalb 1 h): Linie = ×1, gestrichelt = ×2",
"Add to list":"Zur Liste hinzufügen","Reject":"Ablehnen","Close":"Schließen","Copy address":"Adresse kopieren","Copied":"Kopiert","time":"Zeit","token":"Token","rank":"Rang","ETH on curve":"ETH auf der Kurve","entry, ETH":"Einstieg, ETH","peak 1m":"Hoch 1 min","peak 5m":"Hoch 5 min","peak 1h":"Hoch 1 h","peak 24h":"Hoch 24 h","to peak 1h":"bis Hoch 1 h","min 10m":"Tief 10 min","dd before ×2":"Rückgang vor ×2","pool":"Pool","yes":"ja","Reason for rejection":"Grund der Ablehnung","manual":"manuell","manual, from card":"manuell, aus Karte","manual (selection)":"manuell (Auswahl)","nothing to add":"nichts hinzuzufügen","Add":"Hinzufügen","addresses to list":"Adressen zur Liste","filter: ":"Filter: ","added ":"hinzugefügt ",", removed ":", entfernt ",", waiting ":", wartend ",", at risk ":", gefährdet ",", in list ":", in Liste ","recomputing…":"wird neu berechnet…","no report":"kein Bericht",
"min signals":"min. Signale","min excess over market":"min. Überschuss über Markt","max rug share (10 min)":"max. Rug-Anteil (10 min)","min lower bound":"min. Untergrenze","list size":"Listengröße","remove if excess <":"entfernen, wenn Überschuss <","consecutive days to enter":"Tage in Folge bis Aufnahme","consecutive days below to exit":"Tage in Folge darunter bis Ausschluss","days in quarantine before recheck":"Tage Quarantäne bis erneute Prüfung",
"n":"Signale","sigs/day":"Signale/Tag","hit (raw)":"Treffer (roh)","exp. market":"erw. Markt","lower bound":"Untergrenze","excess":"Überschuss","rug 10m":"Rug 10 min","buyer #":"Käufer Nr.","% threshold":"% Schwelle","peak 1h med":"Hoch 1 h Median","time to peak":"Zeit bis Hoch","peak 24h med":"Hoch 24 h Median","peak 24h mean":"Hoch 24 h Mittel","best share":"bester Anteil","reached pool":"Pool erreicht","×5/24h":"×5/24 h","×10/24h":"×10/24 h","val n":"Val. n","val hit ":"Val. Treffer ","flag":"Flag","status":"Status","added at":"hinzugefügt am",
"signals ":"Signale ","signals/day":"Signale/Tag","excess over market":"Überschuss über Markt","× market":"× Markt","buyer rank":"Käuferrang","% threshold before entry":"% Schwelle vor Einstieg","peak 1h (med.)":"Hoch 1 h (Median)","time to peak, s":"Zeit bis Hoch, s","peak 24h (med.)":"Hoch 24 h (Median)","peak 24h (mean)":"Hoch 24 h (Mittel)","best signal share":"Anteil des besten Signals","×5 in 24h":"×5 in 24 h","validation: n":"Validierung: n","validation: hit":"Validierung: Treffer","hit shrunk":"Treffer (geschrumpft)","peak 24h (max)":"Hoch 24 h (max)","peak 7d (med.)":"Hoch 7 d (Median)","dd before ×2 (med.)":"Rückgang vor ×2 (Median)","time to ×2 (med.)":"Zeit bis ×2 (Median)",
}
H = {
"n":"Anzahl der Signale (Erstkäufe) dieser Wallet im Auswahlzeitraum","raw":"Anteil der Signale mit Treffer (fast: ×2 innerhalb 1 h; Picker: Pool oder ×5 in 24 h, ≥×1,5 ab unserem Einstieg)","p_exp":"Erwartete Trefferquote eines zufälligen Käufers an denselben Kurvenpositionen wie diese Wallet","low":"Wilson-80%-Untergrenze der Trefferquote — die pessimistische Lesart","excess":"Untergrenze minus Erwartung: der Vorsprung gegenüber dem Markt. Das Hauptkriterium.","lift":"Rohe Trefferquote geteilt durch Erwartung","rug":"Anteil der Signale, bei denen der Preis innerhalb von 10 Minuten unter 0,2× fiel","med_rank":"Medianposition unter den Käufern des Tokens (5 = meist der 5. Käufer)","med_curve_frac":"Medianer Anteil der Graduierungsschwelle, der beim Kauf der Wallet bereits eingesammelt war","med_ath_1h":"Medianes Hoch innerhalb 1 h relativ zu unserem Einstieg 2 s nach der Wallet","med_t_ath_1h":"Mediane Zeit vom Einstieg bis zum 1-h-Hoch","med_ath_24h":"Medianes Hoch innerhalb 24 h","mean_ath_24h":"Mittleres Hoch innerhalb 24 h — empfindlich gegenüber dem Rand (×10+)","best_share_24h":"Anteil des gesamten 24-h-Gewinns der Wallet, der aus ihrem einzelnen besten Signal stammt (niedriger = konsistenter)","grad_rate":"Anteil der Tokens der Wallet, die in einen Pool graduiert sind","p_x5_24h":"Anteil der Signale, die innerhalb 24 h ×5 erreichen","val_n":"Signale im Validierungszeitraum (letzte 7 Tage, nicht für die Auswahl genutzt)","val_raw":"Trefferquote im Validierungszeitraum — die Zahl, die Glück entlarvt","sigs_per_day":"Durchschnittliche Signale pro Tag","flag":"contract = Adresse hat Code; check-code / eoa-bot = mutmaßlicher Bot",
}
