T = {
"How to read the table":"Cómo leer la tabla","Show hints on column headers":"Mostrar ayudas en los encabezados","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"Cada billetera se compara con compradores en la misma posición de la curva; el criterio principal es el exceso — tasa de acierto pesimista menos la del mercado. La validación es un periodo nunca usado para la selección.",
"Compact columns":"Columnas compactas","All columns":"Todas las columnas",
"Sign in":"Iniciar sesión","API keys":"Claves API","Key name":"Nombre de la clave","Create key":"Crear clave","name":"nombre","prefix":"prefijo","calls":"llamadas","last used":"último uso","Revoke":"Revocar","No keys yet":"Aún no hay claves","Copy the key now — it is shown once":"Copia la clave ahora — solo se muestra una vez",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"Usa la clave en la cabecera X-API-Key. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 solicitudes por minuto.",
"My lists":"Mis listas","New list name":"Nombre de la nueva lista","Create":"Crear","Select or create a list":"Selecciona o crea una lista","Add selected to my list…":"Añadir seleccionados a mi lista…","Add to my list…":"Añadir a mi lista…","Which list?":"¿A qué lista?","Remove":"Quitar","Delete list":"Eliminar lista","Delete this list?":"¿Eliminar esta lista?","Notes":"Notas","Save":"Guardar","added to":"añadido a","wallets":"billeteras","Sign in to keep your own lists":"Inicia sesión para guardar tus propias listas","Rename":"Renombrar","No lists yet":"Aún no hay listas","Export":"Exportar","History":"Historial",
"Overview":"Resumen","List":"Lista","Candidates":"Candidatos","Log":"Registro","Rejected":"Rechazados","Lists":"Listas externas","Rules":"Reglas","Fast · ×2 in 1 h":"Fast · ×2 en 1 h","Pickers · pool or ×5 in 24 h":"Pickers · pool o ×5 en 24 h","Top candidates":"Mejores candidatos","Open candidates →":"Abrir candidatos →","Your list":"Tu lista","Apply rules":"Aplicar reglas","Export list":"Exportar lista","Recompute":"Recalcular","Market baselines":"Referencias del mercado","Market baselines (last recompute)":"Referencias del mercado (último cálculo)","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"Tasa de acierto de todo el mercado por posición en la curva — cada billetera se compara con compradores en la misma posición.",
"address…":"dirección…","all":"todos","Add all matching to list":"Añadir todos los coincidentes a la lista","Add selected":"Añadir seleccionados","Reject selected":"Rechazar seleccionados","Save rules":"Guardar reglas",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"Listas externas de lists/*.txt evaluadas con nuestro scoring. «Acierto» = ×2 en 1 h (fast) o pool/×5 (picker) sobre todas las señales de la lista; «esperado» = lo que daría el mercado en las mismas posiciones de la curva.",
"signals":"señales","candidates":"candidatos","in list":"en la lista","rejected":"rechazados","data as of":"datos a","empty":"vacío","sign out":"cerrar sesión","Signals":"Señales","Wallets":"Billeteras","In list":"En la lista","Data":"Datos","addresses in profile":"direcciones en el perfil","showing first":"mostrando los primeros","Filter: matching":"Filtro: coincidentes","of":"de","Preset: fast":"Preajuste: fast","Preset: pickers":"Preajuste: pickers","Soft preset":"Preajuste suave","Reset":"Restablecer","from":"de","to":"a","in list ":"en la lista ","rejected ":"rechazados ",
"added":"añadido","removed":"eliminado","restored":"restaurado","recompute":"recálculo","rules":"reglas","when":"cuándo","action":"acción","address":"dirección","profile":"perfil","reason":"motivo","by":"por","recheck after":"revisar después de","restore":"restaurar","list":"lista","size":"tamaño","in data":"en los datos","n≥5":"n≥5","hit":"acierto","expected":"esperado","×market":"×mercado","median excess":"exceso mediano","share excess>0":"proporción exceso>0","top-100":"top 100","top-500":"top 500","ranked":"clasificados","median rank":"rango mediano","val signals":"señales de validación","val hit":"acierto validación","val expected":"esperado validación","no data — put lists into lists/*.txt and recompute":"sin datos — coloca las listas en lists/*.txt y recalcula","Profile “fast”":"Perfil «fast»","Profile “pickers”":"Perfil «pickers»","Signals (":"Señales (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"cada punto es una señal en el tiempo; altura = log₂(pico en 1 h): línea = ×1, discontinua = ×2",
"Add to list":"Añadir a la lista","Reject":"Rechazar","Close":"Cerrar","Copy address":"Copiar dirección","Copied":"Copiado","time":"hora","token":"token","rank":"rango","ETH on curve":"ETH en la curva","entry, ETH":"entrada, ETH","peak 1m":"pico 1 min","peak 5m":"pico 5 min","peak 1h":"pico 1 h","peak 24h":"pico 24 h","to peak 1h":"hasta el pico 1 h","min 10m":"mínimo 10 min","dd before ×2":"caída antes de ×2","pool":"pool","yes":"sí","Reason for rejection":"Motivo del rechazo","manual":"manual","manual, from card":"manual, desde la ficha","manual (selection)":"manual (selección)","nothing to add":"nada que añadir","Add":"Añadir","addresses to list":"direcciones a la lista","filter: ":"filtro: ","added ":"añadidos ",", removed ":", eliminados ",", waiting ":", en espera ",", at risk ":", en riesgo ",", in list ":", en la lista ","recomputing…":"recalculando…","no report":"sin informe",
"min signals":"señales mín.","min excess over market":"exceso mín. sobre el mercado","max rug share (10 min)":"proporción máx. de rug (10 min)","min lower bound":"límite inferior mín.","list size":"tamaño de la lista","remove if excess <":"quitar si exceso <","consecutive days to enter":"días consecutivos para entrar","consecutive days below to exit":"días consecutivos por debajo para salir","days in quarantine before recheck":"días en cuarentena antes de revisar",
"n":"señales","sigs/day":"señales/día","hit (raw)":"acierto (bruto)","exp. market":"mercado esp.","lower bound":"límite inf.","excess":"exceso","rug 10m":"rug 10 min","buyer #":"comprador n.º","% threshold":"% del umbral","peak 1h med":"pico 1 h med.","time to peak":"tiempo hasta el pico","peak 24h med":"pico 24 h med.","peak 24h mean":"pico 24 h media","best share":"mejor proporción","reached pool":"llegó al pool","×5/24h":"×5/24 h","×10/24h":"×10/24 h","val n":"val. n","val hit ":"val. acierto ","flag":"marca","status":"estado","added at":"añadido el",
"signals ":"señales ","signals/day":"señales/día","excess over market":"exceso sobre el mercado","× market":"× mercado","buyer rank":"rango de comprador","% threshold before entry":"% del umbral antes de entrar","peak 1h (med.)":"pico 1 h (med.)","time to peak, s":"tiempo hasta el pico, s","peak 24h (med.)":"pico 24 h (med.)","peak 24h (mean)":"pico 24 h (media)","best signal share":"proporción de la mejor señal","×5 in 24h":"×5 en 24 h","validation: n":"validación: n","validation: hit":"validación: acierto","hit shrunk":"acierto (contraído)","peak 24h (max)":"pico 24 h (máx.)","peak 7d (med.)":"pico 7 d (med.)","dd before ×2 (med.)":"caída antes de ×2 (med.)","time to ×2 (med.)":"tiempo hasta ×2 (med.)",
}
H = {
"n":"Número de señales (primeras compras) de esta billetera en el periodo de selección","raw":"Proporción de señales acertadas (fast: ×2 en 1 h; picker: pool o ×5 en 24 h, ≥×1,5 desde nuestra entrada)","p_exp":"Tasa de acierto esperada de un comprador aleatorio en las mismas posiciones de la curva que esta billetera","low":"Límite inferior de Wilson al 80 % de la tasa de acierto — la lectura pesimista","excess":"Límite inferior menos lo esperado: la ventaja sobre el mercado. El criterio principal.","lift":"Tasa de acierto bruta dividida por la esperada","rug":"Proporción de señales en las que el precio cayó por debajo de 0,2× en 10 minutos","med_rank":"Posición mediana entre los compradores del token (5 = normalmente el 5.º comprador)","med_curve_frac":"Proporción mediana del umbral de graduación ya recaudada cuando compró la billetera","med_ath_1h":"Pico mediano en 1 h respecto a nuestra entrada 2 s después de la billetera","med_t_ath_1h":"Tiempo mediano desde la entrada hasta el pico de 1 h","med_ath_24h":"Pico mediano en 24 h","mean_ath_24h":"Pico medio en 24 h — sensible a la cola (×10+)","best_share_24h":"Proporción de la ganancia total en 24 h que proviene de su única mejor señal (más bajo = más consistente)","grad_rate":"Proporción de tokens de la billetera que graduaron a un pool","p_x5_24h":"Proporción de señales que alcanzan ×5 en 24 h","val_n":"Señales en el periodo de validación (últimos 7 días, no usados para la selección)","val_raw":"Tasa de acierto en el periodo de validación — el número que delata la suerte","sigs_per_day":"Promedio de señales por día","flag":"contract = la dirección tiene código; check-code / eoa-bot = posible bot",
}
