T = {
"How to read the table":"Comment lire le tableau","Show hints on column headers":"Afficher les indications dans les en-têtes","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"Chaque portefeuille est comparé aux acheteurs à la même position sur la courbe ; le critère principal est l’excédent — taux de réussite pessimiste moins taux du marché. La validation est une période jamais utilisée pour la sélection.",
"Compact columns":"Colonnes compactes","All columns":"Toutes les colonnes",
"Sign in":"Se connecter","API keys":"Clés API","Key name":"Nom de la clé","Create key":"Créer une clé","name":"nom","prefix":"préfixe","calls":"appels","last used":"dernière utilisation","Revoke":"Révoquer","No keys yet":"Aucune clé pour l’instant","Copy the key now — it is shown once":"Copiez la clé maintenant — elle n’est affichée qu’une fois",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"Utilisez la clé dans l’en-tête X-API-Key. Points d’accès : /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requêtes par minute.",
"My lists":"Mes listes","New list name":"Nom de la nouvelle liste","Create":"Créer","Select or create a list":"Sélectionnez ou créez une liste","Add selected to my list…":"Ajouter la sélection à ma liste…","Add to my list…":"Ajouter à ma liste…","Which list?":"Quelle liste ?","Remove":"Retirer","Delete list":"Supprimer la liste","Delete this list?":"Supprimer cette liste ?","Notes":"Notes","Save":"Enregistrer","added to":"ajouté à","wallets":"portefeuilles","Sign in to keep your own lists":"Connectez-vous pour conserver vos propres listes","Rename":"Renommer","No lists yet":"Aucune liste pour l’instant","Export":"Exporter","History":"Historique",
"Overview":"Aperçu","List":"Liste","Candidates":"Candidats","Log":"Journal","Rejected":"Rejetés","Lists":"Listes externes","Rules":"Règles","Fast · ×2 in 1 h":"Fast · ×2 en 1 h","Pickers · pool or ×5 in 24 h":"Pickers · pool ou ×5 en 24 h","Top candidates":"Meilleurs candidats","Open candidates →":"Ouvrir les candidats →","Your list":"Votre liste","Apply rules":"Appliquer les règles","Export list":"Exporter la liste","Recompute":"Recalculer","Market baselines":"Références du marché","Market baselines (last recompute)":"Références du marché (dernier calcul)","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"Taux de réussite de l’ensemble du marché par position sur la courbe — chaque portefeuille est comparé aux acheteurs à la même position.",
"address…":"adresse…","all":"tous","Add all matching to list":"Ajouter tous les résultats à la liste","Add selected":"Ajouter la sélection","Reject selected":"Rejeter la sélection","Save rules":"Enregistrer les règles",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"Listes externes de lists/*.txt évaluées par notre scoring. « Réussite » = ×2 en 1 h (fast) ou pool/×5 (picker) sur tous les signaux de la liste ; « attendu » = ce que le marché donnerait aux mêmes positions sur la courbe.",
"signals":"signaux","candidates":"candidats","in list":"dans la liste","rejected":"rejetés","data as of":"données au","empty":"vide","sign out":"se déconnecter","Signals":"Signaux","Wallets":"Portefeuilles","In list":"Dans la liste","Data":"Données","addresses in profile":"adresses dans le profil","showing first":"affichage des premiers","Filter: matching":"Filtre : correspondants","of":"sur","Preset: fast":"Préréglage : fast","Preset: pickers":"Préréglage : pickers","Soft preset":"Préréglage souple","Reset":"Réinitialiser","from":"de","to":"à","in list ":"dans la liste ","rejected ":"rejetés ",
"added":"ajouté","removed":"retiré","restored":"rétabli","recompute":"recalcul","rules":"règles","when":"quand","action":"action","address":"adresse","profile":"profil","reason":"raison","by":"par","recheck after":"revérifier après","restore":"rétablir","list":"liste","size":"taille","in data":"dans les données","n≥5":"n≥5","hit":"réussite","expected":"attendu","×market":"×marché","median excess":"excédent médian","share excess>0":"part excédent>0","top-100":"top 100","top-500":"top 500","ranked":"classés","median rank":"rang médian","val signals":"signaux de validation","val hit":"réussite validation","val expected":"attendu validation","no data — put lists into lists/*.txt and recompute":"aucune donnée — placez les listes dans lists/*.txt et recalculez","Profile “fast”":"Profil « fast »","Profile “pickers”":"Profil « pickers »","Signals (":"Signaux (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"chaque point est un signal dans le temps ; hauteur = log₂(pic en 1 h) : ligne = ×1, pointillés = ×2",
"Add to list":"Ajouter à la liste","Reject":"Rejeter","Close":"Fermer","Copy address":"Copier l’adresse","Copied":"Copié","time":"heure","token":"token","rank":"rang","ETH on curve":"ETH sur la courbe","entry, ETH":"entrée, ETH","peak 1m":"pic 1 min","peak 5m":"pic 5 min","peak 1h":"pic 1 h","peak 24h":"pic 24 h","to peak 1h":"jusqu’au pic 1 h","min 10m":"plancher 10 min","dd before ×2":"repli avant ×2","pool":"pool","yes":"oui","Reason for rejection":"Motif du rejet","manual":"manuel","manual, from card":"manuel, depuis la fiche","manual (selection)":"manuel (sélection)","nothing to add":"rien à ajouter","Add":"Ajouter","addresses to list":"adresses à la liste","filter: ":"filtre : ","added ":"ajoutés ",", removed ":", retirés ",", waiting ":", en attente ",", at risk ":", à risque ",", in list ":", dans la liste ","recomputing…":"recalcul en cours…","no report":"aucun rapport",
"min signals":"signaux min.","min excess over market":"excédent min. sur le marché","max rug share (10 min)":"part de rug max. (10 min)","min lower bound":"borne inférieure min.","list size":"taille de la liste","remove if excess <":"retirer si excédent <","consecutive days to enter":"jours consécutifs pour entrer","consecutive days below to exit":"jours consécutifs en dessous pour sortir","days in quarantine before recheck":"jours de quarantaine avant revérification",
"n":"signaux","sigs/day":"signaux/jour","hit (raw)":"réussite (brute)","exp. market":"marché attendu","lower bound":"borne inf.","excess":"excédent","rug 10m":"rug 10 min","buyer #":"acheteur n°","% threshold":"% du seuil","peak 1h med":"pic 1 h méd.","time to peak":"temps jusqu’au pic","peak 24h med":"pic 24 h méd.","peak 24h mean":"pic 24 h moy.","best share":"meilleure part","reached pool":"pool atteint","×5/24h":"×5/24 h","×10/24h":"×10/24 h","val n":"val. n","val hit ":"val. réussite ","flag":"indicateur","status":"statut","added at":"ajouté le",
"signals ":"signaux ","signals/day":"signaux/jour","excess over market":"excédent sur le marché","× market":"× marché","buyer rank":"rang d’acheteur","% threshold before entry":"% du seuil avant entrée","peak 1h (med.)":"pic 1 h (méd.)","time to peak, s":"temps jusqu’au pic, s","peak 24h (med.)":"pic 24 h (méd.)","peak 24h (mean)":"pic 24 h (moy.)","best signal share":"part du meilleur signal","×5 in 24h":"×5 en 24 h","validation: n":"validation : n","validation: hit":"validation : réussite","hit shrunk":"réussite (rétrécie)","peak 24h (max)":"pic 24 h (max)","peak 7d (med.)":"pic 7 j (méd.)","dd before ×2 (med.)":"repli avant ×2 (méd.)","time to ×2 (med.)":"temps jusqu’à ×2 (méd.)",
}
H = {
"n":"Nombre de signaux (premiers achats) de ce portefeuille sur la période de sélection","raw":"Part des signaux réussis (fast : ×2 en 1 h ; picker : pool ou ×5 en 24 h, ≥×1,5 depuis notre entrée)","p_exp":"Taux de réussite attendu d’un acheteur aléatoire aux mêmes positions sur la courbe que ce portefeuille","low":"Borne inférieure de Wilson à 80 % du taux de réussite — la lecture pessimiste","excess":"Borne inférieure moins l’attendu : l’avantage sur le marché. Le critère principal.","lift":"Taux de réussite brut divisé par l’attendu","rug":"Part des signaux où le prix est tombé sous 0,2× en 10 minutes","med_rank":"Position médiane parmi les acheteurs du token (5 = généralement le 5ᵉ acheteur)","med_curve_frac":"Part médiane du seuil de graduation déjà collectée au moment de l’achat","med_ath_1h":"Pic médian en 1 h par rapport à notre entrée 2 s après le portefeuille","med_t_ath_1h":"Temps médian entre l’entrée et le pic à 1 h","med_ath_24h":"Pic médian en 24 h","mean_ath_24h":"Pic moyen en 24 h — sensible à la queue (×10+)","best_share_24h":"Part du gain total sur 24 h provenant du seul meilleur signal (plus bas = plus régulier)","grad_rate":"Part des tokens du portefeuille ayant gradué vers un pool","p_x5_24h":"Part des signaux atteignant ×5 en 24 h","val_n":"Signaux sur la période de validation (7 derniers jours, non utilisés pour la sélection)","val_raw":"Taux de réussite sur la période de validation — le chiffre qui démasque la chance","sigs_per_day":"Nombre moyen de signaux par jour","flag":"contract = l’adresse a du code ; check-code / eoa-bot = bot présumé",
}
