T = {
"How to read the table":"表の読み方","Show hints on column headers":"列見出しにヒントを表示","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"各ウォレットはカーブ上の同じ位置の買い手と比較されます。主要な基準は超過（悲観的ヒット率 − 市場ヒット率）です。検証は選定に一切使わない期間です。",
"Compact columns":"簡易表示","All columns":"全列表示",
"Sign in":"ログイン","API keys":"APIキー","Key name":"キー名","Create key":"キーを作成","name":"名前","prefix":"プレフィックス","calls":"呼び出し数","last used":"最終使用","Revoke":"無効化","No keys yet":"キーはまだありません","Copy the key now — it is shown once":"今すぐキーをコピーしてください — 表示は一度きりです",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"X-API-Key ヘッダーにキーを指定してください。エンドポイント: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots。毎分60リクエストまで。",
"My lists":"マイリスト","New list name":"新しいリスト名","Create":"作成","Select or create a list":"リストを選択または作成","Add selected to my list…":"選択項目をマイリストに追加…","Add to my list…":"マイリストに追加…","Which list?":"どのリストに？","Remove":"除外","Delete list":"リストを削除","Delete this list?":"このリストを削除しますか？","Notes":"メモ","Save":"保存","added to":"追加先:","wallets":"ウォレット","Sign in to keep your own lists":"ログインすると自分のリストを保存できます","Rename":"名前を変更","No lists yet":"リストはまだありません","Export":"エクスポート","History":"履歴",
"Overview":"概要","List":"リスト","Candidates":"候補","Log":"ログ","Rejected":"除外済み","Lists":"外部リスト","Rules":"ルール","Fast · ×2 in 1 h":"Fast · 1時間以内に×2","Pickers · pool or ×5 in 24 h":"Picker · プール到達または24時間以内に×5","Top candidates":"上位候補","Open candidates →":"候補を開く →","Your list":"あなたのリスト","Apply rules":"ルールを適用","Export list":"リストをエクスポート","Recompute":"再計算","Market baselines":"市場ベースライン","Market baselines (last recompute)":"市場ベースライン（最終再計算）","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"カーブ位置ごとの市場全体のヒット率 — 各ウォレットは同じ位置の買い手と比較されます。",
"address…":"アドレス…","all":"すべて","Add all matching to list":"一致する項目をすべてリストに追加","Add selected":"選択項目を追加","Reject selected":"選択項目を除外","Save rules":"ルールを保存",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"lists/*.txt の外部リストを当方のスコアリングで評価。「ヒット」= 1時間以内に×2（fast）またはプール/×5（picker）、リスト全シグナル対象；「期待値」= 同じカーブ位置で市場が与える値。",
"signals":"シグナル","candidates":"候補","in list":"リスト内","rejected":"除外","data as of":"データ時点","empty":"空","sign out":"ログアウト","Signals":"シグナル","Wallets":"ウォレット","In list":"リスト内","Data":"データ","addresses in profile":"プロファイル内のアドレス","showing first":"先頭を表示","Filter: matching":"フィルター: 一致","of":"/","Preset: fast":"プリセット: fast","Preset: pickers":"プリセット: picker","Soft preset":"緩めのプリセット","Reset":"リセット","from":"から","to":"まで","in list ":"リスト内 ","rejected ":"除外 ",
"added":"追加","removed":"削除","restored":"復元","recompute":"再計算","rules":"ルール","when":"日時","action":"操作","address":"アドレス","profile":"プロファイル","reason":"理由","by":"実行者","recheck after":"再確認日","restore":"復元","list":"リスト","size":"件数","in data":"データあり","n≥5":"n≥5","hit":"ヒット","expected":"期待値","×market":"×市場","median excess":"超過（中央値）","share excess>0":"超過>0 の割合","top-100":"上位100","top-500":"上位500","ranked":"順位あり","median rank":"順位（中央値）","val signals":"検証シグナル","val hit":"検証ヒット","val expected":"検証期待値","no data — put lists into lists/*.txt and recompute":"データなし — lists/*.txt にリストを置いて再計算してください","Profile “fast”":"プロファイル「fast」","Profile “pickers”":"プロファイル「picker」","Signals (":"シグナル (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"各点は時系列のシグナル；高さ = log₂(1時間以内のピーク)：実線 = ×1、破線 = ×2",
"Add to list":"リストに追加","Reject":"除外","Close":"閉じる","Copy address":"アドレスをコピー","Copied":"コピーしました","time":"時刻","token":"トークン","rank":"順位","ETH on curve":"カーブ上のETH","entry, ETH":"エントリー, ETH","peak 1m":"ピーク1分","peak 5m":"ピーク5分","peak 1h":"ピーク1時間","peak 24h":"ピーク24時間","to peak 1h":"1時間ピークまで","min 10m":"安値10分","dd before ×2":"×2前の下落","pool":"プール","yes":"はい","Reason for rejection":"除外理由","manual":"手動","manual, from card":"手動（カードから）","manual (selection)":"手動（選択）","nothing to add":"追加するものがありません","Add":"追加","addresses to list":"件のアドレスをリストへ","filter: ":"フィルター: ","added ":"追加 ",", removed ":", 削除 ",", waiting ":", 待機 ",", at risk ":", リスク ",", in list ":", リスト内 ","recomputing…":"再計算中…","no report":"レポートなし",
"min signals":"最小シグナル数","min excess over market":"市場超過の最小値","max rug share (10 min)":"ラグ率の最大値（10分）","min lower bound":"下限の最小値","list size":"リストサイズ","remove if excess <":"超過がこの値未満なら除外","consecutive days to enter":"追加までの連続日数","consecutive days below to exit":"除外までの連続未達日数","days in quarantine before recheck":"再確認までの隔離日数",
"n":"シグナル","sigs/day":"シグナル/日","hit (raw)":"ヒット（生）","exp. market":"期待市場","lower bound":"下限","excess":"超過","rug 10m":"ラグ10分","buyer #":"買い手 #","% threshold":"閾値%","peak 1h med":"ピーク1h 中央値","time to peak":"ピークまでの時間","peak 24h med":"ピーク24h 中央値","peak 24h mean":"ピーク24h 平均","best share":"最良シェア","reached pool":"プール到達","×5/24h":"×5/24h","×10/24h":"×10/24h","val n":"検証 n","val hit ":"検証ヒット ","flag":"フラグ","status":"状態","added at":"追加日時",
"signals ":"シグナル ","signals/day":"シグナル/日","excess over market":"市場超過","× market":"× 市場","buyer rank":"買い手順位","% threshold before entry":"エントリー前の閾値%","peak 1h (med.)":"ピーク1h（中央値）","time to peak, s":"ピークまでの秒数","peak 24h (med.)":"ピーク24h（中央値）","peak 24h (mean)":"ピーク24h（平均）","best signal share":"最良シグナルのシェア","×5 in 24h":"24h以内に×5","validation: n":"検証: n","validation: hit":"検証: ヒット","hit shrunk":"ヒット（縮小推定）","peak 24h (max)":"ピーク24h（最大）","peak 7d (med.)":"ピーク7日（中央値）","dd before ×2 (med.)":"×2前の下落（中央値）","time to ×2 (med.)":"×2までの時間（中央値）",
}
H = {
"n":"選定期間中のこのウォレットのシグナル（初回購入）数","raw":"ヒットしたシグナルの割合（fast: 1時間以内に×2；picker: プール到達または24時間以内に×5、当方エントリーから≥×1.5）","p_exp":"このウォレットと同じカーブ位置でのランダムな買い手の期待ヒット率","low":"ヒット率の Wilson 80% 下限 — 悲観的な見積もり","excess":"下限から期待値を引いた値：市場に対する優位。主要な基準。","lift":"生のヒット率 ÷ 期待値","rug":"10分以内に価格が0.2×を下回ったシグナルの割合","med_rank":"トークンの買い手の中での順位の中央値（5 = 通常5番目の買い手）","med_curve_frac":"ウォレット購入時点で既に集まっていた卒業閾値の割合の中央値","med_ath_1h":"ウォレットの2秒後の当方エントリーに対する1時間以内ピークの中央値","med_t_ath_1h":"エントリーから1時間ピークまでの時間の中央値","med_ath_24h":"24時間以内ピークの中央値","mean_ath_24h":"24時間以内ピークの平均 — テール（×10+）に敏感","best_share_24h":"ウォレットの24時間総利益のうち最良シグナル1件が占める割合（低いほど安定）","grad_rate":"プールへ卒業したウォレットのトークンの割合","p_x5_24h":"24時間以内に×5に達したシグナルの割合","val_n":"検証期間（直近7日、選定には未使用）のシグナル数","val_raw":"検証期間のヒット率 — 運を見抜く数字","sigs_per_day":"1日あたりの平均シグナル数","flag":"contract = コードを持つアドレス；check-code / eoa-bot = ボットの疑い",
}
