T = {
"How to read the table":"표 읽는 법","Show hints on column headers":"열 머리글에 도움말 표시","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"모든 지갑은 커브의 같은 위치에 있는 매수자와 비교됩니다. 핵심 기준은 초과 — 비관적 적중률에서 시장 적중률을 뺀 값입니다. 검증은 선택에 전혀 사용되지 않은 기간입니다.",
"Compact columns":"간단 보기","All columns":"전체 열",
"Sign in":"로그인","API keys":"API 키","Key name":"키 이름","Create key":"키 만들기","name":"이름","prefix":"접두사","calls":"호출 수","last used":"마지막 사용","Revoke":"폐기","No keys yet":"아직 키가 없습니다","Copy the key now — it is shown once":"지금 키를 복사하세요 — 한 번만 표시됩니다",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"X-API-Key 헤더에 키를 넣어 사용하세요. 엔드포인트: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 분당 60회.",
"My lists":"내 목록","New list name":"새 목록 이름","Create":"만들기","Select or create a list":"목록을 선택하거나 만드세요","Add selected to my list…":"선택 항목을 내 목록에 추가…","Add to my list…":"내 목록에 추가…","Which list?":"어느 목록에?","Remove":"제거","Delete list":"목록 삭제","Delete this list?":"이 목록을 삭제할까요?","Notes":"메모","Save":"저장","added to":"추가됨:","wallets":"지갑","Sign in to keep your own lists":"로그인하면 나만의 목록을 저장할 수 있습니다","Rename":"이름 바꾸기","No lists yet":"아직 목록이 없습니다","Export":"내보내기","History":"기록",
"Overview":"개요","List":"목록","Candidates":"후보","Log":"로그","Rejected":"제외됨","Lists":"외부 목록","Rules":"규칙","Fast · ×2 in 1 h":"패스트 · 1시간 내 ×2","Pickers · pool or ×5 in 24 h":"피커 · 풀 진입 또는 24시간 내 ×5","Top candidates":"상위 후보","Open candidates →":"후보 전체 보기 →","Your list":"내 리스트","Apply rules":"규칙 적용","Export list":"목록 내보내기","Recompute":"재계산","Market baselines":"시장 기준선","Market baselines (last recompute)":"시장 기준선 (마지막 재계산)","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"커브 위치별 전체 시장의 적중률 — 모든 지갑은 같은 위치의 매수자와 비교됩니다.",
"address…":"주소…","all":"전체","Add all matching to list":"일치하는 항목 모두 목록에 추가","Add selected":"선택 항목 추가","Reject selected":"선택 항목 제외","Save rules":"규칙 저장",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"lists/*.txt의 외부 목록을 우리 스코어링으로 평가. “적중” = 1시간 내 ×2(패스트) 또는 풀/×5(피커), 목록의 모든 신호 기준; “기대치” = 같은 커브 위치에서 시장이 주었을 값.",
"signals":"신호","candidates":"후보","in list":"목록에 있음","rejected":"제외됨","data as of":"데이터 기준","empty":"비어 있음","sign out":"로그아웃","Signals":"신호","Wallets":"지갑","In list":"목록 내","Data":"데이터","addresses in profile":"프로필의 주소","showing first":"처음 표시","Filter: matching":"필터: 일치","of":"/","Preset: fast":"프리셋: 패스트","Preset: pickers":"프리셋: 피커","Soft preset":"완화 프리셋","Reset":"초기화","from":"부터","to":"까지","in list ":"목록 내 ","rejected ":"제외 ",
"added":"추가됨","removed":"제거됨","restored":"복원됨","recompute":"재계산","rules":"규칙","when":"시각","action":"작업","address":"주소","profile":"프로필","reason":"사유","by":"실행자","recheck after":"재검토 시점","restore":"복원","list":"목록","size":"크기","in data":"데이터 내","n≥5":"n≥5","hit":"적중","expected":"기대치","×market":"×시장","median excess":"초과 중앙값","share excess>0":"초과>0 비율","top-100":"상위 100","top-500":"상위 500","ranked":"순위 있음","median rank":"순위 중앙값","val signals":"검증 신호","val hit":"검증 적중","val expected":"검증 기대치","no data — put lists into lists/*.txt and recompute":"데이터 없음 — lists/*.txt에 목록을 넣고 재계산하세요","Profile “fast”":"프로필 “패스트”","Profile “pickers”":"프로필 “피커”","Signals (":"신호 (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"각 점은 시간순 신호; 높이 = log₂(1시간 내 고점): 실선 = ×1, 점선 = ×2",
"Add to list":"목록에 추가","Reject":"제외","Close":"닫기","Copy address":"주소 복사","Copied":"복사됨","time":"시각","token":"토큰","rank":"순위","ETH on curve":"커브 내 ETH","entry, ETH":"진입, ETH","peak 1m":"고점 1분","peak 5m":"고점 5분","peak 1h":"고점 1시간","peak 24h":"고점 24시간","to peak 1h":"1시간 고점까지","min 10m":"저점 10분","dd before ×2":"×2 전 낙폭","pool":"풀","yes":"예","Reason for rejection":"제외 사유","manual":"수동","manual, from card":"수동, 카드에서","manual (selection)":"수동 (선택)","nothing to add":"추가할 항목 없음","Add":"추가","addresses to list":"개 주소를 목록에","filter: ":"필터: ","added ":"추가 ",", removed ":", 제거 ",", waiting ":", 대기 ",", at risk ":", 위험 ",", in list ":", 목록 내 ","recomputing…":"재계산 중…","no report":"보고서 없음",
"min signals":"최소 신호 수","min excess over market":"시장 대비 최소 초과","max rug share (10 min)":"최대 러그 비율 (10분)","min lower bound":"최소 하한","list size":"목록 크기","remove if excess <":"초과가 이보다 작으면 제거","consecutive days to enter":"진입까지 연속 일수","consecutive days below to exit":"이탈까지 연속 미달 일수","days in quarantine before recheck":"재검토 전 격리 일수",
"n":"신호","sigs/day":"신호/일","hit (raw)":"적중 (원시)","exp. market":"기대 시장","lower bound":"하한","excess":"초과","rug 10m":"러그 10분","buyer #":"매수자 #","% threshold":"% 임계치","peak 1h med":"고점 1h 중앙","time to peak":"고점까지 시간","peak 24h med":"고점 24h 중앙","peak 24h mean":"고점 24h 평균","best share":"최고 비중","reached pool":"풀 도달","×5/24h":"×5/24h","×10/24h":"×10/24h","val n":"검증 n","val hit ":"검증 적중 ","flag":"플래그","status":"상태","added at":"추가 시각",
"signals ":"신호 ","signals/day":"신호/일","excess over market":"시장 대비 초과","× market":"× 시장","buyer rank":"매수자 순위","% threshold before entry":"진입 전 임계치 %","peak 1h (med.)":"고점 1h (중앙)","time to peak, s":"고점까지 시간, 초","peak 24h (med.)":"고점 24h (중앙)","peak 24h (mean)":"고점 24h (평균)","best signal share":"최고 신호 비중","×5 in 24h":"24h 내 ×5","validation: n":"검증: n","validation: hit":"검증: 적중","hit shrunk":"적중 (축소)","peak 24h (max)":"고점 24h (최대)","peak 7d (med.)":"고점 7일 (중앙)","dd before ×2 (med.)":"×2 전 낙폭 (중앙)","time to ×2 (med.)":"×2까지 시간 (중앙)",
}
H = {
"n":"선택 기간 동안 이 지갑의 신호(첫 매수) 수","raw":"적중한 신호 비율 (패스트: 1시간 내 ×2; 피커: 풀 진입 또는 24시간 내 ×5, 우리 진입 대비 ≥×1.5)","p_exp":"이 지갑과 같은 커브 위치에서 무작위 매수자의 기대 적중률","low":"적중률의 Wilson 80% 하한 — 비관적 추정치","excess":"하한에서 기대치를 뺀 값: 시장 대비 우위. 핵심 기준.","lift":"원시 적중률 ÷ 기대치","rug":"10분 내 가격이 0.2× 아래로 떨어진 신호 비율","med_rank":"토큰 매수자 중 순위의 중앙값 (5 = 보통 5번째 매수자)","med_curve_frac":"지갑이 매수한 시점에 이미 모인 졸업 임계치 비율의 중앙값","med_ath_1h":"지갑보다 2초 늦은 우리 진입 대비 1시간 내 고점의 중앙값","med_t_ath_1h":"진입에서 1시간 고점까지 시간의 중앙값","med_ath_24h":"24시간 내 고점의 중앙값","mean_ath_24h":"24시간 내 고점의 평균 — 꼬리(×10+)에 민감","best_share_24h":"지갑의 24시간 총 수익 중 최고 신호 하나가 차지하는 비율 (낮을수록 일관적)","grad_rate":"풀로 졸업한 지갑 토큰의 비율","p_x5_24h":"24시간 내 ×5에 도달한 신호 비율","val_n":"검증 기간(최근 7일, 선택에 미사용)의 신호 수","val_raw":"검증 기간의 적중률 — 운을 걸러내는 숫자","sigs_per_day":"하루 평균 신호 수","flag":"contract = 코드가 있는 주소; check-code / eoa-bot = 봇 의심",
}
