T = {
"How to read the table":"Cara membaca jadual","Show hints on column headers":"Tunjukkan petunjuk pada tajuk lajur","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"Setiap dompet dibandingkan dengan pembeli pada kedudukan lengkung yang sama; kriteria utama ialah lebihan — kadar kena pesimis tolak kadar pasaran. Pengesahan ialah tempoh yang tidak pernah digunakan untuk pemilihan.",
"Compact columns":"Lajur ringkas","All columns":"Semua lajur",
"Sign in":"Log masuk","API keys":"Kunci API","Key name":"Nama kunci","Create key":"Cipta kunci","name":"nama","prefix":"awalan","calls":"panggilan","last used":"terakhir digunakan","Revoke":"Batalkan","No keys yet":"Belum ada kunci","Copy the key now — it is shown once":"Salin kunci sekarang — dipaparkan sekali sahaja",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"Gunakan kunci dalam pengepala X-API-Key. Titik akhir: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 permintaan seminit.",
"My lists":"Senarai saya","New list name":"Nama senarai baharu","Create":"Cipta","Select or create a list":"Pilih atau cipta senarai","Add selected to my list…":"Tambah pilihan ke senarai saya…","Add to my list…":"Tambah ke senarai saya…","Which list?":"Senarai mana?","Remove":"Buang","Delete list":"Padam senarai","Delete this list?":"Padam senarai ini?","Notes":"Nota","Save":"Simpan","added to":"ditambah ke","wallets":"dompet","Sign in to keep your own lists":"Log masuk untuk menyimpan senarai anda sendiri","Rename":"Namakan semula","No lists yet":"Belum ada senarai","Export":"Eksport","History":"Sejarah",
"Overview":"Gambaran","List":"Senarai","Candidates":"Calon","Log":"Log","Rejected":"Ditolak","Lists":"Senarai luar","Rules":"Peraturan","Fast · ×2 in 1 h":"Fast · ×2 dalam 1 jam","Pickers · pool or ×5 in 24 h":"Picker · pool atau ×5 dalam 24 jam","Top candidates":"Calon teratas","Open candidates →":"Buka calon →","Your list":"Senarai anda","Apply rules":"Guna peraturan","Export list":"Eksport senarai","Recompute":"Kira semula","Market baselines":"Garis asas pasaran","Market baselines (last recompute)":"Garis asas pasaran (kiraan terakhir)","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"Kadar kena seluruh pasaran mengikut kedudukan lengkung — setiap dompet diukur berbanding pembeli pada kedudukan yang sama.",
"address…":"alamat…","all":"semua","Add all matching to list":"Tambah semua yang sepadan ke senarai","Add selected":"Tambah pilihan","Reject selected":"Tolak pilihan","Save rules":"Simpan peraturan",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"Senarai luar daripada lists/*.txt dinilai dengan pemarkahan kami. “Kena” = ×2 dalam 1 jam (fast) atau pool/×5 (picker) atas semua isyarat senarai; “dijangka” = apa yang pasaran beri pada kedudukan lengkung yang sama.",
"signals":"isyarat","candidates":"calon","in list":"dalam senarai","rejected":"ditolak","data as of":"data setakat","empty":"kosong","sign out":"log keluar","Signals":"Isyarat","Wallets":"Dompet","In list":"Dalam senarai","Data":"Data","addresses in profile":"alamat dalam profil","showing first":"memaparkan","Filter: matching":"Penapis: sepadan","of":"daripada","Preset: fast":"Pratetap: fast","Preset: pickers":"Pratetap: picker","Soft preset":"Pratetap longgar","Reset":"Set semula","from":"dari","to":"hingga","in list ":"dalam senarai ","rejected ":"ditolak ",
"added":"ditambah","removed":"dibuang","restored":"dipulihkan","recompute":"kira semula","rules":"peraturan","when":"bila","action":"tindakan","address":"alamat","profile":"profil","reason":"sebab","by":"oleh","recheck after":"semak semula selepas","restore":"pulihkan","list":"senarai","size":"saiz","in data":"dalam data","n≥5":"n≥5","hit":"kena","expected":"dijangka","×market":"×pasaran","median excess":"lebihan median","share excess>0":"bahagian lebihan>0","top-100":"100 teratas","top-500":"500 teratas","ranked":"berpangkat","median rank":"pangkat median","val signals":"isyarat pengesahan","val hit":"kena pengesahan","val expected":"dijangka pengesahan","no data — put lists into lists/*.txt and recompute":"tiada data — letakkan senarai dalam lists/*.txt dan kira semula","Profile “fast”":"Profil “fast”","Profile “pickers”":"Profil “picker”","Signals (":"Isyarat (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"setiap titik ialah isyarat mengikut masa; tinggi = log₂(puncak dalam 1 jam): garis = ×1, putus-putus = ×2",
"Add to list":"Tambah ke senarai","Reject":"Tolak","Close":"Tutup","Copy address":"Salin alamat","Copied":"Disalin","time":"masa","token":"token","rank":"pangkat","ETH on curve":"ETH pada lengkung","entry, ETH":"masuk, ETH","peak 1m":"puncak 1m","peak 5m":"puncak 5m","peak 1h":"puncak 1j","peak 24h":"puncak 24j","to peak 1h":"ke puncak 1j","min 10m":"minimum 10m","dd before ×2":"jatuh sebelum ×2","pool":"pool","yes":"ya","Reason for rejection":"Sebab penolakan","manual":"manual","manual, from card":"manual, dari kad","manual (selection)":"manual (pilihan)","nothing to add":"tiada apa untuk ditambah","Add":"Tambah","addresses to list":"alamat ke senarai","filter: ":"penapis: ","added ":"ditambah ",", removed ":", dibuang ",", waiting ":", menunggu ",", at risk ":", berisiko ",", in list ":", dalam senarai ","recomputing…":"mengira semula…","no report":"tiada laporan",
"min signals":"min. isyarat","min excess over market":"min. lebihan atas pasaran","max rug share (10 min)":"maks. bahagian rug (10 min)","min lower bound":"min. batas bawah","list size":"saiz senarai","remove if excess <":"buang jika lebihan <","consecutive days to enter":"hari berturut-turut untuk masuk","consecutive days below to exit":"hari berturut-turut di bawah untuk keluar","days in quarantine before recheck":"hari kuarantin sebelum semakan semula",
"n":"isyarat","sigs/day":"isyarat/hari","hit (raw)":"kena (mentah)","exp. market":"jangkaan pasaran","lower bound":"batas bawah","excess":"lebihan","rug 10m":"rug 10m","buyer #":"pembeli #","% threshold":"% ambang","peak 1h med":"puncak 1j median","time to peak":"masa ke puncak","peak 24h med":"puncak 24j median","peak 24h mean":"puncak 24j purata","best share":"bahagian terbaik","reached pool":"capai pool","×5/24h":"×5/24j","×10/24h":"×10/24j","val n":"pengesahan n","val hit ":"pengesahan kena ","flag":"bendera","status":"status","added at":"ditambah pada",
"signals ":"isyarat ","signals/day":"isyarat/hari","excess over market":"lebihan atas pasaran","× market":"× pasaran","buyer rank":"pangkat pembeli","% threshold before entry":"% ambang sebelum masuk","peak 1h (med.)":"puncak 1j (median)","time to peak, s":"masa ke puncak, s","peak 24h (med.)":"puncak 24j (median)","peak 24h (mean)":"puncak 24j (purata)","best signal share":"bahagian isyarat terbaik","×5 in 24h":"×5 dalam 24j","validation: n":"pengesahan: n","validation: hit":"pengesahan: kena","hit shrunk":"kena (dikecilkan)","peak 24h (max)":"puncak 24j (maks)","peak 7d (med.)":"puncak 7h (median)","dd before ×2 (med.)":"jatuh sebelum ×2 (median)","time to ×2 (med.)":"masa ke ×2 (median)",
}
H = {
"n":"Bilangan isyarat (belian pertama) dompet ini dalam tempoh pemilihan","raw":"Bahagian isyarat yang kena (fast: ×2 dalam 1 jam; picker: pool atau ×5 dalam 24 jam, ≥×1.5 dari kemasukan kami)","p_exp":"Kadar kena dijangka bagi pembeli rawak pada kedudukan lengkung yang sama dengan dompet ini","low":"Batas bawah Wilson 80% bagi kadar kena — bacaan pesimis","excess":"Batas bawah tolak jangkaan: kelebihan atas pasaran. Kriteria utama.","lift":"Kadar kena mentah dibahagi jangkaan","rug":"Bahagian isyarat yang harganya jatuh bawah 0.2× dalam 10 minit","med_rank":"Kedudukan median dalam kalangan pembeli token (5 = biasanya pembeli ke-5)","med_curve_frac":"Bahagian median ambang graduasi yang telah terkumpul ketika dompet membeli","med_ath_1h":"Puncak median dalam 1 jam relatif kepada kemasukan kami 2 s selepas dompet","med_t_ath_1h":"Masa median dari kemasukan ke puncak 1 jam","med_ath_24h":"Puncak median dalam 24 jam","mean_ath_24h":"Puncak purata dalam 24 jam — sensitif kepada ekor (×10+)","best_share_24h":"Bahagian keuntungan 24 jam dompet yang datang daripada satu isyarat terbaiknya (lebih rendah = lebih konsisten)","grad_rate":"Bahagian token dompet yang bergraduasi ke pool","p_x5_24h":"Bahagian isyarat yang mencapai ×5 dalam 24 jam","val_n":"Isyarat dalam tempoh pengesahan (7 hari terakhir, tidak digunakan untuk pemilihan)","val_raw":"Kadar kena dalam tempoh pengesahan — angka yang menangkap nasib","sigs_per_day":"Purata isyarat sehari","flag":"contract = alamat mempunyai kod; check-code / eoa-bot = disyaki bot",
}
