T = {
"How to read the table":"Cách đọc bảng","Show hints on column headers":"Hiện gợi ý trên tiêu đề cột","Every wallet is compared with buyers at the same position on the curve; the main criterion is excess — the pessimistic hit rate minus the market rate. Validation is a period never used for selection.":"Mỗi ví được so với người mua ở cùng vị trí trên đường cong; tiêu chí chính là vượt trội — tỷ lệ trúng bi quan trừ tỷ lệ thị trường. Kiểm định là giai đoạn không bao giờ dùng để chọn.",
"Compact columns":"Cột gọn","All columns":"Tất cả cột",
"Sign in":"Đăng nhập","API keys":"Khóa API","Key name":"Tên khóa","Create key":"Tạo khóa","name":"tên","prefix":"tiền tố","calls":"lượt gọi","last used":"dùng lần cuối","Revoke":"Thu hồi","No keys yet":"Chưa có khóa","Copy the key now — it is shown once":"Sao chép khóa ngay — chỉ hiển thị một lần",
"Use the key in the X-API-Key header. Endpoints: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 requests per minute.":"Dùng khóa trong header X-API-Key. Endpoint: /v1/summary · /v1/list/{fast|picker|all} · /v1/candidates/{fast|picker}?limit=100 · /v1/wallet/{address} · /v1/snapshots. 60 yêu cầu mỗi phút.",
"My lists":"Danh sách của tôi","New list name":"Tên danh sách mới","Create":"Tạo","Select or create a list":"Chọn hoặc tạo danh sách","Add selected to my list…":"Thêm mục đã chọn vào danh sách của tôi…","Add to my list…":"Thêm vào danh sách của tôi…","Which list?":"Danh sách nào?","Remove":"Xóa khỏi","Delete list":"Xóa danh sách","Delete this list?":"Xóa danh sách này?","Notes":"Ghi chú","Save":"Lưu","added to":"đã thêm vào","wallets":"ví","Sign in to keep your own lists":"Đăng nhập để lưu danh sách riêng","Rename":"Đổi tên","No lists yet":"Chưa có danh sách","Export":"Xuất","History":"Lịch sử",
"Overview":"Tổng quan","List":"Danh sách","Candidates":"Ứng viên","Log":"Nhật ký","Rejected":"Bị loại","Lists":"DS ngoài","Rules":"Quy tắc","Fast · ×2 in 1 h":"Fast · ×2 trong 1 giờ","Pickers · pool or ×5 in 24 h":"Picker · lên pool hoặc ×5 trong 24 giờ","Top candidates":"Ứng viên hàng đầu","Open candidates →":"Mở danh sách ứng viên →","Your list":"Danh sách của bạn","Apply rules":"Áp dụng quy tắc","Export list":"Xuất danh sách","Recompute":"Tính lại","Market baselines":"Đường cơ sở thị trường","Market baselines (last recompute)":"Đường cơ sở thị trường (lần tính gần nhất)","Hit rate of the whole market by curve position — every wallet is measured against buyers at the same position.":"Tỷ lệ trúng của toàn thị trường theo vị trí trên đường cong — mỗi ví được so với người mua ở cùng vị trí.",
"address…":"địa chỉ…","all":"tất cả","Add all matching to list":"Thêm tất cả mục khớp vào danh sách","Add selected":"Thêm mục đã chọn","Reject selected":"Loại mục đã chọn","Save rules":"Lưu quy tắc",
"External lists from lists/*.txt against our scoring. “Hit” = ×2 within 1 h (fast) or pool/×5 (picker) over all of the list's signals; “expected” = what the market would give at the same curve positions.":"Danh sách ngoài từ lists/*.txt chấm theo hệ thống của chúng tôi. “Trúng” = ×2 trong 1 giờ (fast) hoặc pool/×5 (picker) trên toàn bộ tín hiệu của danh sách; “kỳ vọng” = thị trường sẽ cho gì ở cùng vị trí trên đường cong.",
"signals":"tín hiệu","candidates":"ứng viên","in list":"trong danh sách","rejected":"bị loại","data as of":"dữ liệu tính đến","empty":"trống","sign out":"đăng xuất","Signals":"Tín hiệu","Wallets":"Ví","In list":"Trong danh sách","Data":"Dữ liệu","addresses in profile":"địa chỉ trong hồ sơ","showing first":"hiển thị","Filter: matching":"Bộ lọc: khớp","of":"/","Preset: fast":"Mẫu: fast","Preset: pickers":"Mẫu: picker","Soft preset":"Mẫu nới lỏng","Reset":"Đặt lại","from":"từ","to":"đến","in list ":"trong danh sách ","rejected ":"bị loại ",
"added":"đã thêm","removed":"đã xóa","restored":"đã khôi phục","recompute":"tính lại","rules":"quy tắc","when":"thời điểm","action":"hành động","address":"địa chỉ","profile":"hồ sơ","reason":"lý do","by":"bởi","recheck after":"kiểm tra lại sau","restore":"khôi phục","list":"danh sách","size":"kích thước","in data":"có dữ liệu","n≥5":"n≥5","hit":"trúng","expected":"kỳ vọng","×market":"×thị trường","median excess":"vượt trội (trung vị)","share excess>0":"tỷ lệ vượt>0","top-100":"top-100","top-500":"top-500","ranked":"có xếp hạng","median rank":"hạng trung vị","val signals":"tín hiệu kiểm định","val hit":"trúng kiểm định","val expected":"kỳ vọng kiểm định","no data — put lists into lists/*.txt and recompute":"không có dữ liệu — đặt danh sách vào lists/*.txt và tính lại","Profile “fast”":"Hồ sơ “fast”","Profile “pickers”":"Hồ sơ “picker”","Signals (":"Tín hiệu (","each dot is a signal in time; height = log₂(peak within 1 h): line = ×1, dashed = ×2":"mỗi chấm là một tín hiệu theo thời gian; chiều cao = log₂(đỉnh trong 1 giờ): nét liền = ×1, nét đứt = ×2",
"Add to list":"Thêm vào danh sách","Reject":"Loại","Close":"Đóng","Copy address":"Sao chép địa chỉ","Copied":"Đã sao chép","time":"thời gian","token":"token","rank":"hạng","ETH on curve":"ETH trên đường cong","entry, ETH":"vào lệnh, ETH","peak 1m":"đỉnh 1p","peak 5m":"đỉnh 5p","peak 1h":"đỉnh 1g","peak 24h":"đỉnh 24g","to peak 1h":"tới đỉnh 1g","min 10m":"đáy 10p","dd before ×2":"sụt trước ×2","pool":"pool","yes":"có","Reason for rejection":"Lý do loại","manual":"thủ công","manual, from card":"thủ công, từ thẻ","manual (selection)":"thủ công (chọn)","nothing to add":"không có gì để thêm","Add":"Thêm","addresses to list":"địa chỉ vào danh sách","filter: ":"bộ lọc: ","added ":"đã thêm ",", removed ":", đã xóa ",", waiting ":", đang chờ ",", at risk ":", có nguy cơ ",", in list ":", trong danh sách ","recomputing…":"đang tính lại…","no report":"chưa có báo cáo",
"min signals":"tín hiệu tối thiểu","min excess over market":"vượt thị trường tối thiểu","max rug share (10 min)":"tỷ lệ rug tối đa (10 phút)","min lower bound":"cận dưới tối thiểu","list size":"kích thước danh sách","remove if excess <":"xóa nếu vượt trội <","consecutive days to enter":"số ngày liên tiếp để vào","consecutive days below to exit":"số ngày liên tiếp dưới ngưỡng để ra","days in quarantine before recheck":"số ngày cách ly trước khi kiểm tra lại",
"n":"tín hiệu","sigs/day":"tín hiệu/ngày","hit (raw)":"trúng (thô)","exp. market":"kỳ vọng TT","lower bound":"cận dưới","excess":"vượt trội","rug 10m":"rug 10p","buyer #":"người mua #","% threshold":"% ngưỡng","peak 1h med":"đỉnh 1g trung vị","time to peak":"thời gian tới đỉnh","peak 24h med":"đỉnh 24g trung vị","peak 24h mean":"đỉnh 24g trung bình","best share":"tỷ trọng tốt nhất","reached pool":"lên pool","×5/24h":"×5/24g","×10/24h":"×10/24g","val n":"kiểm định n","val hit ":"kiểm định trúng ","flag":"cờ","status":"trạng thái","added at":"thêm lúc",
"signals ":"tín hiệu ","signals/day":"tín hiệu/ngày","excess over market":"vượt thị trường","× market":"× thị trường","buyer rank":"hạng người mua","% threshold before entry":"% ngưỡng trước khi vào","peak 1h (med.)":"đỉnh 1g (trung vị)","time to peak, s":"thời gian tới đỉnh, giây","peak 24h (med.)":"đỉnh 24g (trung vị)","peak 24h (mean)":"đỉnh 24g (trung bình)","best signal share":"tỷ trọng tín hiệu tốt nhất","×5 in 24h":"×5 trong 24g","validation: n":"kiểm định: n","validation: hit":"kiểm định: trúng","hit shrunk":"trúng (co rút)","peak 24h (max)":"đỉnh 24g (tối đa)","peak 7d (med.)":"đỉnh 7 ngày (trung vị)","dd before ×2 (med.)":"sụt trước ×2 (trung vị)","time to ×2 (med.)":"thời gian tới ×2 (trung vị)",
}
H = {
"n":"Số tín hiệu (lần mua đầu) của ví này trong kỳ chọn mẫu","raw":"Tỷ lệ tín hiệu trúng (fast: ×2 trong 1 giờ; picker: lên pool hoặc ×5 trong 24 giờ, ≥×1.5 so với điểm vào của chúng tôi)","p_exp":"Tỷ lệ trúng kỳ vọng của một người mua ngẫu nhiên ở cùng vị trí trên đường cong với ví này","low":"Cận dưới Wilson 80% của tỷ lệ trúng — ước lượng bi quan","excess":"Cận dưới trừ kỳ vọng: lợi thế so với thị trường. Tiêu chí chính.","lift":"Tỷ lệ trúng thô chia cho kỳ vọng","rug":"Tỷ lệ tín hiệu mà giá rơi dưới 0.2× trong 10 phút","med_rank":"Vị trí trung vị trong số người mua token (5 = thường là người mua thứ 5)","med_curve_frac":"Tỷ lệ trung vị của ngưỡng tốt nghiệp đã gom được khi ví mua","med_ath_1h":"Đỉnh trung vị trong 1 giờ so với điểm vào của chúng tôi 2 giây sau ví","med_t_ath_1h":"Thời gian trung vị từ khi vào đến đỉnh 1 giờ","med_ath_24h":"Đỉnh trung vị trong 24 giờ","mean_ath_24h":"Đỉnh trung bình trong 24 giờ — nhạy với phần đuôi (×10+)","best_share_24h":"Tỷ trọng của tín hiệu tốt nhất trong tổng lãi 24 giờ của ví (thấp hơn = ổn định hơn)","grad_rate":"Tỷ lệ token của ví đã tốt nghiệp lên pool","p_x5_24h":"Tỷ lệ tín hiệu đạt ×5 trong 24 giờ","val_n":"Tín hiệu trong kỳ kiểm định (7 ngày gần nhất, không dùng để chọn)","val_raw":"Tỷ lệ trúng trong kỳ kiểm định — con số lọc ra may mắn","sigs_per_day":"Số tín hiệu trung bình mỗi ngày","flag":"contract = địa chỉ có mã; check-code / eoa-bot = nghi là bot",
}
